### ISSUE TITLE
Параметры методов

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#10]
Можно просто эту же модель и передать в метод сервиса и тогда не нужно много аргументов прописывать

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/controller/ProductController.java#L35-L39

**Comment by SoulHowl** [comment]
Аналогично 

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/controller/OrderController.java#L31-L35

**Comment by Fursanov** [comment]
Есть
