### ISSUE TITLE
Controllers dependency injection

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#11]
Как и с сервисами, навешиваешь autowired на конструктор, куда пердаешь переменные сервисов и т.п., аннотация @AllArgsConstructor тогда не нужна.

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/controller/BrandController.java#L13-L20

**Comment by SoulHowl** [comment]
аналогично для других контроллеров

**Comment by Fursanov** [comment]
Есть
