### ISSUE TITLE
проверка на существующего пользователя

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#12]
Учитывая, что с фронта приходят имя и почта пользователя, хорошо бы сделать проверку на уникальность той же почты

https://github.com/Fursanov/Practice/blob/e8036faaf91849776a9b0152d7560a73cb9b8473/src/main/java/com/example/onlineMarket/services/UserService.java#L22-L24

**Comment by SoulHowl** [comment]
ну и тогда выбрасывать ошибку типа "пользователь с такими данными уже существует"

**Comment by Fursanov** [comment]
У меня на уровне бд Email unique стоит, в любом случае не даст создать

**Comment by Fursanov** [comment]
Просто ловить ошибку?

**Comment by SoulHowl** [comment]
Ловишь и респонс на фронт кидаешь с каким-то сообщением (при помощи того же ExceptionHandler).

**Comment by SoulHowl** [comment]
Аналогично сделай и при создании магазинов одинаковыми именами.
