### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#6]
Лучше будет создать конструктор (в который передаешь все аргументы)  и аннотацию @Autowired привязать к конструктору и не прописывать тогда аннотации @AllArgsConstructor, @NoArgsConstructor для сервиса. 

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/services/BrandService.java#L13-L20

**Comment by SoulHowl** [comment]
это касается всех сервисов

**Comment by Fursanov** [comment]
Есть
