### ISSUE TITLE
Константы

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#7]
Можно вынести эту повторяющуюся строку "Brands is not exists with the given id: " в константу

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/services/BrandService.java#L26-L28

**Comment by SoulHowl** [comment]
повыности такие строки в константы во всех сервисах

**Comment by Fursanov** [comment]
Есть
