### ISSUE TITLE
Возвращаемое значение из метода сервиса

### ISSUE THREAD

**Issue by SoulHowl** [Fursanov/Practice#8]
Возвращаемое значение не используется

https://github.com/Fursanov/Practice/blob/96a79c085e75cb7befbc85e68c683f09fb35bf48/src/main/java/com/example/onlineMarket/services/OrderService.java#L53-L59

**Comment by SoulHowl** [comment]
Аналогично для других delete-методов сервисов

**Comment by Fursanov** [comment]
Убрал сделал void
